version: '3.8'

services:
  metabase:
    image: metabase/metabase:v0.51.4.4 # be careful with the version to avoid compatibility issues on production
    container_name: metabase
    restart: always
    ports:
      - '80:3000'
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_password
      MB_DB_HOST: db
    depends_on:
      - db
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  db:
    image: postgres:13 # be careful with the version to avoid compatibility issues on production
    container_name: metabase_db
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - ${DATABASE_LOCAL_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U metabase']
      interval: 10s
      timeout: 5s
      retries: 5
